export default {
	name: 'resource',
	title: 'Downloadable Resources',
	type: 'document',
	groups: [
		{ name: 'content', title: 'Content' },
		{ name: 'download', title: 'Download & Form' },
		{ name: 'display', title: 'Display' },
	],
	fields: [
		{
			name: 'title',
			title: 'Resource Title',
			type: 'string',
			description: "e.g. Father's Heart → Beloved Identity",
			validation: (Rule: any) => Rule.required(),
			group: 'content',
		},
		{
			name: 'slug',
			title: 'Slug',
			type: 'slug',
			options: { source: 'title', maxLength: 96 },
			validation: (Rule: any) => Rule.required(),
		},
		{
			name: 'shortDescription',
			title: 'Short Description',
			type: 'text',
			rows: 2,
			description: 'One or two sentences used in preview cards.',
			group: 'content',
		},
		{
			name: 'longDescription',
			title: 'Long Description',
			type: 'array',
			of: [{ type: 'block' }],
			description: 'Full description shown on the download page.',
			group: 'content',
		},
		{
			name: 'coverImage',
			title: 'Cover Image',
			type: 'image',
			options: { hotspot: true },
			description: 'Book or resource cover image (upload to Sanity).',
			group: 'content',
		},
		{
			name: 'coverImageUrl',
			title: 'Cover Image URL (External)',
			type: 'url',
			description: 'R2 URL for the cover image — used if Sanity image not uploaded.',
			group: 'content',
		},
		{
			name: 'fileUrl',
			title: 'File URL / Delivery Link',
			type: 'url',
			description: 'Direct download URL or landing page URL for this resource.',
			group: 'download',
		},
		{
			name: 'formHeading',
			title: 'Form Section Heading',
			type: 'string',
			description: 'Heading shown above the download form.',
			group: 'download',
		},
		{
			name: 'formDescription',
			title: 'Form Section Description',
			type: 'text',
			rows: 2,
			description: 'Supporting copy shown above the download form.',
			group: 'download',
		},
		{
			name: 'buttonText',
			title: 'Download Button Text',
			type: 'string',
			description: 'e.g. "Download the Free Book"',
			group: 'download',
		},
		{
			name: 'featured',
			title: 'Featured Resource',
			type: 'boolean',
			initialValue: false,
			description: 'Show this resource on the Download page.',
			group: 'display',
		},
		{
			name: 'order',
			title: 'Display Order',
			type: 'number',
			group: 'display',
		},
	],
	preview: {
		select: { title: 'title', media: 'coverImage' },
	},
};
