// FHB LANGUAGE print editions shown on /print and in the homepage's second cover marquee.
//
// ONLY editions whose press files are FINISHED are listed: interior + case + jacket +
// paperback + metadata sheet present in the language submission set (Drive
// 1faik2I_8shdwAi352TDaSUUtRI4-16jk). 22 as of 2026-10-03. A language whose covers are not
// delivered shows its DESIGNED front (design: true) — Kevin 2026-10-03 — and `ready: false`
// would hide an edition entirely. Kevin 2026-10-03: "Build marquee and /print for 26 languages" —
// the 22 complete + Arabic, Farsi, Urdu (right-to-left, being built) + Tangkhul (hold lifted,
// being built). Flip `ready` (and add its card art) as each cover is delivered.
// Kevin 2026-10-07: "all 33 languages" = the 31 live in the reader + Amharic and Zulu, which
// are `soon: true` — counted and named as coming soon, but no card, page or order form until
// their covers and interiors are BUILT (cover rule 2026-10-06: never a designed front). Every
// shown card is now cut from its built case (lang/v2 for ar fa ur nmf + the five added
// 2026-10-07: ceb pl zh-hans uk yo).
//
// `name` is the edition's own name exactly as its record carries it
// (projects/fhb-print-bible/editions/<code>.json → edition_name), which is also the title
// printed on its cover. `english` is the submission set's folder name.
// Prices: the top table of every language metadata sheet lists US $99.99 hardback / $79.99
// paperback (22/22 read 2026-10-03).
// `amazon`: a binding's URL only when its Amazon listing is LIVE; absent = the shared
// disabled placeholder (BuyControls). Now from the registry (the daily Amazon watch adds new
// listings, each verified by reading the listing's ISBN-13 back). 2026-10-07: looked up by each binding's ISBN-13
// (amazon-search.mjs, sequential) and kept only where the hit's title names the language AND
// the binding — 25 languages live, some in one binding only (fil PB; fr de sw HB); ceb pl
// zh-hans uk ur yo not on Amazon yet. ASINs are the /dp/ ids.
// Card art: FHB/print/lang/v1/lang-<code>-{360,600,1200}.webp, cut from each language's
// DELIVERED case PDF (md5-matched to the submission set) by
// projects/fhb-lang-covers/cards/build_lang_cards.py — the same house renderer as every
// other /print card.
import registry from './edition-registry.json' with { type: 'json' };

export interface LanguageEdition {
	code: string;
	name: string;
	english: string;
	/** card line: "For " + the sheet's For box (fors.d/lang-<code>.json), as approved */
	sub: string;
	amazon?: { hardback?: string; paperback?: string };
	/** false = press files not delivered yet: counted in the 26, never shown. */
	ready?: boolean;
	/** card art is the edition's DESIGNED front (locked 74-cover set, language-bible-titles) because
	 *  its press cover is not delivered yet (Kevin 2026-10-03: use it meanwhile). Swap to the
	 *  delivered case PDF via build_lang_cards.py under a NEW R2 key when it lands. */
	design?: boolean;
	/** coming soon (Kevin 2026-10-07): counted in the 33 and named, never given a card, page or
	 *  order form — no built cover or interior yet. Drop it when both land. */
	soon?: boolean;
	/** right-to-left script */
	rtl?: boolean;
}

export const LANG_HB = 99.99;
export const LANG_PB = 79.99;

// THE LIST IS NOT TYPED HERE ANY MORE (Kevin 2026-10-07, "1 yes 2. a"). It is
// src/data/edition-registry.json, GENERATED by `/home/deploy/bin/fhb-chain.py edition-emit` from
// the facts the work itself writes: the publisher's Ingram submission log (an edition is listed
// once BOTH bindings carry an Ingram CSS id), ISBNS.json, the edition decks and the locked title
// master (name), fors.d (English name + the For line), the delivered press files on Drive (card
// cut from the BUILT case), and claude-config/editions/amazon-listings.json (Amazon, ISBN-matched).
// Amharic and Zulu are listed early by Kevin's ruling and render as `soon` until their covers are
// built. The registry is alphabetical by English name, as /print is. Never hand-edit it — fix the
// fact; the edition chain re-emits it and ships it.
export const allLanguageEditions: LanguageEdition[] = registry.editions.map((e) => ({
	code: e.code,
	name: e.name,
	english: e.english,
	sub: e.sub,
	...('rtl' in e && e.rtl ? { rtl: true } : {}),
	...('soon' in e && e.soon ? { soon: true } : {}),
	...('amazon' in e && e.amazon && Object.keys(e.amazon).length ? { amazon: e.amazon } : {}),
}));

/** Every language edition (Kevin's 33), shown or not. */
export const LANGUAGE_EDITION_TOTAL = allLanguageEditions.length;
/** The editions with delivered covers — the only ones any page renders. */
export const languageEditions = allLanguageEditions.filter((l) => l.ready !== false && !l.soon);
/** Named on /print as coming soon; nothing else renders them. */
export const comingSoonEditions = allLanguageEditions.filter((l) => l.soon);

/** URL/data slug for an edition's product page and look-inside: "spanish" → /bibles/spanish-bible/ */
export const langSlug = (l: LanguageEdition) =>
	l.english
		.replace(/\s*\(.*\)/, '')
		.toLowerCase()
		.replace(/[^a-z]+/g, '-');
